apiVersion: v1
kind: ConfigMap
metadata:
    name: environment
data:
    # each key is a deployment name
    # value is a JSON array of {name, value} object
    deployment-name: |
        [
            {
                "name": "ENV_VAR_1",
                "value": "env_var_1_value"
            },
            {
                "name": "ENV_VAR_2",
                "value": "env_var_2_value"
            }
        ]