apiVersion: v1
kind: Service
metadata:
    name: http-server
spec:
    type: NodePort
    selector:
        app: http-server
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080